sparat-2NE1/delivery

build.gradle
src/main/java/com/sparta/delivery/domain/card/entity/Card.java
src/main/java/com/sparta/delivery/domain/config/SwaggerConfig.java
src/main/java/com/sparta/delivery/domain/payment/entity/Payment.java

card entity
payment entity
swagger config 설정

feat : card, payment entity 구현, swagger config 설정

---

src/main/java/com/sparta/delivery/config/SwaggerConfig.java

refactor : swagger 디렉토리 위치 변경

---

src/main/java/com/sparta/delivery/domain/order/entity/Order.java
src/main/java/com/sparta/delivery/domain/review/entity/Review.java

1. 리뷰 entity 생성
2. 주문관리 entity 연관관계 추가

feat: review entity 추가

---

src/main/java/com/sparta/delivery/domain/order/entity/Order.java
src/main/java/com/sparta/delivery/domain/order/enums/OrderType.java

fix: order entity 수정
requirements -> enum 삭제
delivery_Type 삭제 후 OrderType에 통합

fix: order entity 수정

---

src/main/java/com/sparta/delivery/config/SecurityConfig.java
src/main/java/com/sparta/delivery/config/jwt/JwtUtil.java
src/main/java/com/sparta/delivery/domain/user/controller/UserController.java
src/main/java/com/sparta/delivery/domain/user/dto/JwtResponseDto.java
src/main/java/com/sparta/delivery/domain/user/dto/LoginRequestDto.java
src/main/java/com/sparta/delivery/domain/user/dto/SignupReqDto.java
src/main/java/com/sparta/delivery/domain/user/entity/User.java
src/main/java/com/sparta/delivery/domain/user/repository/UserRepository.java
src/main/java/com/sparta/delivery/domain/user/service/UserService.java

- /api/user/signin 경로의 POST 요청 처리
- UserReqDto.java 클래스명 변경 -> SignupReqDto.java
- LoginRequestDto 생성
- username, password
- JwtResponseDto 생성
- accessToken
- JwtUtil 구현
- jwt 생성, 검증 기능 구현

<유저, 보안> 로그인 기능 , JWT 발급 구현

---

src/main/java/com/sparta/delivery/domain/delivery_address/DeliveryAddress.java
src/main/java/com/sparta/delivery/domain/user/entity/User.java

feat : DeliveryAddress Entity 구현

---

src/main/java/com/sparta/delivery/config/SwaggerConfig.java
src/main/java/com/sparta/delivery/config/global/exception/ExceptionResponse.java
src/main/java/com/sparta/delivery/config/global/exception/GlobalExceptionHandler.java
src/main/java/com/sparta/delivery/config/global/exception/custom/ForbiddenException.java
src/main/java/com/sparta/delivery/domain/card/entity/Card.java
src/main/java/com/sparta/delivery/domain/card/repository/CardRepository.java
src/main/java/com/sparta/delivery/domain/payment/entity/Payment.java
src/main/java/com/sparta/delivery/domain/payment/repository/PaymentRepository.java

- swagger 설정 변경
- global exception 구현
- custom exception 구현

feat : global exception 설정

---

src/main/java/com/sparta/delivery/domain/order/controller/OrderController.java
src/main/java/com/sparta/delivery/domain/order/dto/OrderRequestDto.java
src/main/java/com/sparta/delivery/domain/order/dto/OrderResponseDto.java
src/main/java/com/sparta/delivery/domain/order/entity/Order.java
src/main/java/com/sparta/delivery/domain/order/repository/OrderRepository.java
src/main/java/com/sparta/delivery/domain/order/service/OrderService.java
src/main/java/com/sparta/delivery/domain/review/entity/Review.java
src/main/java/com/sparta/delivery/domain/review/repository/ReviewRepository.java

Order API
- getOrder
- getUserOrderList
- getStoreOrderList
- deleteOrder
Order
- entity 변수명 수정
Review
- entity 변수명 수정
- repository 추가

feature: order controller, service 개발

---

src/main/java/com/sparta/delivery/domain/region/entity/Region.java
src/main/java/com/sparta/delivery/domain/region/repository/RegionRepository.java
src/main/java/com/sparta/delivery/domain/store/entity/Stores.java
src/main/java/com/sparta/delivery/domain/store/repository/StoreRepository.java

Stores,Region Repository 추가
Id값 uuid전환 및 변수명 수정
Region클래스 localty->locality(오타수정)
id명 카멜케이스수정
컬럼에 not null추가

feat : Stores,Region Repository 추가,Id값 uuid전환 및 변수명 수정

---

src/main/java/com/sparta/delivery/domain/order/dto/OrderResponseDto.java

fix: order dto 수정

---

src/main/java/com/sparta/delivery/config/jwt/JwtAuthenticationFilter.java
src/main/java/com/sparta/delivery/domain/user/dto/UserResDto.java
src/main/java/com/sparta/delivery/domain/user/entity/User.java
src/main/java/com/sparta/delivery/domain/user/repository/UserRepository.java

User 엔티티 식별자  타입 및 카멜케이스 변경 
- 변경 전 Long user_id
- 변경 후 UUID userId
UserRepository 타입 변경
JWT 검증 필터 헤더 정보 추가
- X-Authenticated-User : username
- X-User-Role : role

refactor: User 식별자를 UUID 타입으로 변경하고 JWT 검증 필터에서 사용자 정보 헤더 추가

---

src/main/java/com/sparta/delivery/domain/user/entity/User.java

refactor: User import 경로 변경

---

src/main/java/com/sparta/delivery/domain/payment/entity/Payment.java

refactor : joinColumn name 변경

---

src/main/java/com/sparta/delivery/domain/region/entity/Region.java
src/main/java/com/sparta/delivery/domain/store/entity/Stores.java
src/main/java/com/sparta/delivery/domain/store/repository/StoreRepository.java

엔티티에 @Builder추가
운영지역- 가게  N:1관계반영(Stores,Region엔티티수정)
Repository수정(Stores)

fix: 엔티티 @Builder추가, region-store N:1관계 수정 및 repository수정사항반영

---

src/main/java/com/sparta/delivery/domain/store/repository/StoreRepository.java

List<Stores> findByCategory(Category category); -> List<Stores> findByCategory(Category category); 목록을 받아오도록 수정

fix :storerepository 일부 수정

---

src/main/java/com/sparta/delivery/domain/region/repository/RegionRepository.java
src/main/java/com/sparta/delivery/domain/store/repository/StoreRepository.java

JpaRepository<T, Long>->JpaRepository<T, UUID>

fix: jparepository id값타입 uuid으로 단순수정

---

src/main/java/com/sparta/delivery/domain/region/entity/Region.java
src/main/java/com/sparta/delivery/domain/store/controller/StoreController.java
src/main/java/com/sparta/delivery/domain/store/entity/Stores.java

private long regionid -> private UUID regionid;
private long storeid -> private UUID storeid;

fix : id값 타입변경 long->uuid

---

src/main/java/com/sparta/delivery/domain/store/controller/StoreController.java
src/main/java/com/sparta/delivery/domain/store/repository/StoreRepository.java

List<Stores> findByCityContaining(String city);//시로검색
List<Stores> findByLocalityContaining(String locality);//동으로검색 
삭제

fix:StoreRepository 잘못된 쿼리메서드 삭제

---

src/main/java/com/sparta/delivery/config/global/exception/GlobalExceptionHandler.java
src/main/java/com/sparta/delivery/config/global/exception/custom/DuplicateProductException.java
src/main/java/com/sparta/delivery/domain/product/controller/ProductController.java
src/main/java/com/sparta/delivery/domain/product/dto/ProductRequestDto.java
src/main/java/com/sparta/delivery/domain/product/dto/ProductResponseDto.java
src/main/java/com/sparta/delivery/domain/product/entity/Product.java
src/main/java/com/sparta/delivery/domain/product/repository/ProductRepository.java
src/main/java/com/sparta/delivery/domain/product/service/ProductService.java

- 상품 등록 기능 추가
- 중복 상품 예외 처리를 위한 'DuplicateProductException' 예외 추가

상품 등록 기능 추가

---

src/main/java/com/sparta/delivery/domain/region/entity/Region.java
src/main/java/com/sparta/delivery/domain/store/entity/Stores.java

변경내역
엔티티
regionid->regionId
storeid->storeId
테이블명
reigion->region

fix: regionId,storeId필드명 수정, region테이블명 오타수정

---

src/main/java/com/sparta/delivery/domain/order/controller/OrderController.java
src/main/java/com/sparta/delivery/domain/order/dto/OrderRequestDto.java
src/main/java/com/sparta/delivery/domain/order/dto/OrderResponseDto.java
src/main/java/com/sparta/delivery/domain/order/dto/OrderStatusRequestDto.java
src/main/java/com/sparta/delivery/domain/order/entity/Order.java
src/main/java/com/sparta/delivery/domain/order/repository/OrderRepository.java
src/main/java/com/sparta/delivery/domain/order/service/OrderService.java

1. OrderRequestDto
- Long user_id -> String username
- store_id -> storeId
- delivery_address_id -> deliveryAddressId
- product_id -> productId
2. OrderResponseDto
- order_time -> orderTime
- String orderId -> UUID orderId
- order_type -> orderType
- order_status -> orderStatus
3. orderService, orderController 수정
4. orderRepository 메소드 변수명 수정
5. 주문 api 상세 개발

feature: 주문 API 개발

---

build.gradle
src/main/java/com/sparta/delivery/config/QuerydslConfig.java
src/main/java/com/sparta/delivery/domain/card/controller/CardController.java
src/main/java/com/sparta/delivery/domain/card/dto/RegistrationCardDto.java
src/main/java/com/sparta/delivery/domain/card/entity/Card.java
src/main/java/com/sparta/delivery/domain/card/repository/CardRepository.java
src/main/java/com/sparta/delivery/domain/card/service/CardService.java
src/main/java/com/sparta/delivery/domain/payment/controller/PaymentController.java
src/main/java/com/sparta/delivery/domain/payment/dto/PaymentDto.java
src/main/java/com/sparta/delivery/domain/payment/dto/RegisterPaymentDto.java
src/main/java/com/sparta/delivery/domain/payment/dto/SearchDto.java
src/main/java/com/sparta/delivery/domain/payment/entity/Payment.java
src/main/java/com/sparta/delivery/domain/payment/repository/PaymentRepository.java
src/main/java/com/sparta/delivery/domain/payment/service/PaymentService.java

- /api/card 경로의 POST 요청 처리 - 카드 정보 등록
- /api/card/{card_id} 경로의 GET 요청 처리 - 카드 정보 단일 조회
- /api/card/cards 경로의 GET 요청 처리 - 카드 정보 리스트 조회
- /api/card/{card_id} 경로의 PUT 요청 처리 - 카드 정보 수정
- /api/card/{card_id} 경로의 PATCH 요청 처리 - 카드 삭제
- Card의 필요 정보만 받기 위한 RegistrationCardDto 설정
- Soft Delete 되지 않은 카드 정보만 받도록 JPA 사용
- /api/payment 경로의 POST 요청 처리 - 임시 결제
- /api/payment/{payment_id} 경로의 GET 요청 처리 - 결제 내역 단일 조회
- /api/payment/payments 경로의 GET 요청 처리 - 결제 내역 리스트 조회
- /api/payment/{payment_id} 경로의 PATCH 요청 처리 - 결제 내역 삭제
- 결제를 위한 RegisterPaymentDto 설정
- 조회를 위한 PaymentDto 설정
- 검색을 위한 SearchDto 설정

feat : payment, card API 개발

---

src/main/java/com/sparta/delivery/domain/payment/controller/PaymentController.java
src/main/java/com/sparta/delivery/domain/payment/entity/Payment.java
src/main/java/com/sparta/delivery/domain/payment/repository/PaymentRepository.java
src/main/java/com/sparta/delivery/domain/payment/repository/PaymentRepositoryCustom.java
src/main/java/com/sparta/delivery/domain/payment/repository/PaymentRepositoryCustomImpl.java
src/main/java/com/sparta/delivery/domain/payment/service/PaymentService.java

feat : Querydsl을 사용한 조건부 검색 구현

---

src/main/java/com/sparta/delivery/domain/order/controller/OrderController.java
src/main/java/com/sparta/delivery/domain/order/dto/OrderRequestDto.java
src/main/java/com/sparta/delivery/domain/order/service/OrderService.java

fix: 오류 처리 로직 변경
-> 서우님 코드 참고하여 try-catch문 이용
-> 주문에 필요한 엔티티들 가져오는 것 메소드로 분리

feature: 주문 생성 개발

---

src/main/java/com/sparta/delivery/config/global/exception/GlobalExceptionHandler.java
src/main/java/com/sparta/delivery/config/global/exception/custom/ProductNotFoundException.java
src/main/java/com/sparta/delivery/domain/product/controller/ProductController.java
src/main/java/com/sparta/delivery/domain/product/service/ProductService.java

- 상품 상세 조회 기능 구현
- 존재하지 않는 상품 조회 시 처리를 위한 'ProductNotFoundException' 커스텀 예외 정의

상품 상세 조회 기능 구현

---

src/main/java/com/sparta/delivery/domain/store/controller/StoreController.java
src/main/java/com/sparta/delivery/domain/store/dto/StoreReqDto.java
src/main/java/com/sparta/delivery/domain/store/dto/StoreResDto.java
src/main/java/com/sparta/delivery/domain/store/repository/StoreRepository.java
src/main/java/com/sparta/delivery/domain/store/service/StoreService.java

feat : 가게 등록 기능 구현

---

src/main/java/com/sparta/delivery/domain/store/controller/StoreController.java
src/main/java/com/sparta/delivery/domain/store/service/StoreService.java

- 가게리스트 단일 조회 구현
- 가게리스트 목록 조회 구현

feat: 가게리스트 조회 구현

---

src/main/java/com/sparta/delivery/domain/user/controller/UserController.java
src/main/java/com/sparta/delivery/domain/user/dto/UserSearchReqDto.java
src/main/java/com/sparta/delivery/domain/user/repository/UserRepository.java
src/main/java/com/sparta/delivery/domain/user/service/UserService.java
src/test/java/com/sparta/delivery/userTest/UserServiceTest.java

- 기존 'getUsers' 메서드를 페이징 및 QueryDSL을 활용하도록 변경
- 'UserSearchReqDto' 를 통해 페이징 및 검색 조건을 처리
- 'UserServiceTest' 의 동작 오류 수정

<유저>   Usre Search 기능 구현

---

src/main/java/com/sparta/delivery/domain/store/controller/StoreController.java
src/main/java/com/sparta/delivery/domain/store/service/StoreService.java

- 가게 수정 기능 추가
- 가게 삭제 기능 추가
- 가게 등록 부분 코드 오타수정

feat : 가게수정 및 삭제기능 추가, 

---

src/main/java/com/sparta/delivery/domain/store/controller/StoreController.java
src/main/java/com/sparta/delivery/domain/store/service/StoreService.java

feat:가게 검색기능 추가

---

src/test/java/com/sparta/delivery/userTest/UserServiceTest.java

<유저> Test 코드 작성 

---

src/main/java/com/sparta/delivery/domain/product/controller/ProductController.java
src/main/java/com/sparta/delivery/domain/product/dto/ProductUpdateRequestDto.java
src/main/java/com/sparta/delivery/domain/product/entity/Product.java
src/main/java/com/sparta/delivery/domain/product/service/ProductService.java

상품 정보 변경 기능 구현

---

src/main/java/com/sparta/delivery/domain/delivery_address/controller/DeliveryAddressController.java
src/main/java/com/sparta/delivery/domain/delivery_address/dto/AddressReqDto.java
src/main/java/com/sparta/delivery/domain/delivery_address/dto/AddressResDto.java
src/main/java/com/sparta/delivery/domain/delivery_address/entity/DeliveryAddress.java
src/main/java/com/sparta/delivery/domain/delivery_address/repository/DeliveryAddressRepository.java
src/main/java/com/sparta/delivery/domain/delivery_address/service/DeliveryAddressService.java
src/main/java/com/sparta/delivery/domain/user/controller/UserController.java
src/main/java/com/sparta/delivery/domain/user/entity/User.java

- /api/delivery-addresses 경로의 POST 요청 처리
- @AuthenticationPrincipal을 사용하여 작성자 확인
- AddressReqDto 및 AddressResDto DTO 구현
- 하나의 유저는 3개의 배송지를 가질 수 있음

<배송지> create 기능 구현

---

src/main/java/com/sparta/delivery/domain/delivery_address/controller/DeliveryAddressController.java
src/main/java/com/sparta/delivery/domain/delivery_address/dto/AddressSearchDto.java
src/main/java/com/sparta/delivery/domain/delivery_address/repository/DeliveryAddressRepository.java
src/main/java/com/sparta/delivery/domain/delivery_address/service/DeliveryAddressService.java

- /api/delivery-addresses 경로의 GET 요청을 처리
- 페이징 및 QueryDSL을 활용하여 검색 및 페이지네이션 구현
- AddressSearchDto 를 통해 페이징 및 검색 조건을 처리

<배송지>DeliveryAddress 리스트 검색 기능 구현

---

src/main/java/com/sparta/delivery/domain/region/controller/RegionController.java
src/main/java/com/sparta/delivery/domain/region/dto/RegionReqDto.java
src/main/java/com/sparta/delivery/domain/region/dto/RegionResDto.java
src/main/java/com/sparta/delivery/domain/region/service/RegionService.java
src/main/java/com/sparta/delivery/domain/store/entity/Stores.java

feature
- 운영지역 등록 기능 api 개발
- 운영지역 리스트조회 기능 api 개발
- 운영지역 단일 조회 기능 api 개발

feat:운영 지역 등록, 운영지역 조회 추가

---

src/main/java/com/sparta/delivery/domain/order/controller/OrderController.java
src/main/java/com/sparta/delivery/domain/order/dto/OrderRequestDto.java
src/main/java/com/sparta/delivery/domain/order/dto/OrderResponseDto.java
src/main/java/com/sparta/delivery/domain/order/entity/Order.java
src/main/java/com/sparta/delivery/domain/order/enums/OrderStatus.java
src/main/java/com/sparta/delivery/domain/order/repository/OrderRepository.java
src/main/java/com/sparta/delivery/domain/order/service/OrderService.java

주문에서 API 테스트 안되는 오류 해결
주문 상태 enum 변경 -> ORDER_CANCEL(주문 취소) 추가
주문 삭제 로직에 5분 이내 주문만 취소 가능한 제어로직 추가
주문 변경 로직에 5분 이내 주문만 취소 가능한 제어로직 삭제 -> 결제 대기 상태면 변경 가능
OrderService -> createOrder, deleteOrder 반환값 void로 변경

fix: 주문 오류 수정 및 기타 사항 변경

---

src/main/java/com/sparta/delivery/domain/order/service/OrderService.java

order.setOrderStatus(OrderStatus.ORDER_CANCEL);  추가

fix: 주문 취소 OrderStatus 변경 코드 추가

---

src/main/java/com/sparta/delivery/domain/region/controller/RegionController.java
src/main/java/com/sparta/delivery/domain/region/entity/Region.java
src/main/java/com/sparta/delivery/domain/region/repository/RegionRepository.java
src/main/java/com/sparta/delivery/domain/region/service/RegionService.java
src/main/java/com/sparta/delivery/domain/store/repository/StoreRepository.java

-운영지역 수정(업데이트) 기능 추가
- 운영지역 검색 기능 추가
- 운영지역 삭제 기능 추가
- 조회시 deletedAt여부 검사해서 조회하도록 수정

feat:운영지역 업데이트,검색,삭제기능 추가, 조회때 deletedAt검사하도록 수정

---

src/main/java/com/sparta/delivery/domain/card/service/CardService.java
src/main/java/com/sparta/delivery/domain/payment/controller/PaymentController.java
src/main/java/com/sparta/delivery/domain/payment/service/PaymentService.java
src/test/java/com/sparta/delivery/cardTest/CardServiceTest.java
src/test/java/com/sparta/delivery/paymentTest/PaymentServiceTest.java

- 카드 등록 성공
- 카드 등록 실패 : 카드 정보 누락
- 카드 등록 실패 : 이미 등록된 카드
- 카드 단일 조회 성공
- 카드 단일 조회 실패 : 존재하지 않는 카드
- 카드 리스트 조회 성공
- 카드 정보 업데이트 성공
- 카드 삭제 성공
- 카드 삭제 실패 : 존재하지 않는 카드
- 결제 성공
- 결제 실패 : 이미 결제된 주문
- 결제 내역 조회 성공
- 결제 내역 조회 실패 : 결제 내역 없음
- 전체 결제 내역 조회
- 전체 결제 내역 조회 실패 : 결제 내역 없음
- 결제 내역 검색 성공
- 결제 내역 삭제 성공
- 결제 내역 삭제 실패 : 결제 정보 없음
- 삭제된 유저 체크

feat : Card & Payment 테스트 코드 작성

---

src/main/java/com/sparta/delivery/domain/product/controller/ProductController.java
src/main/java/com/sparta/delivery/domain/product/repository/ProductRepository.java
src/main/java/com/sparta/delivery/domain/product/service/ProductService.java

상품 검색 기능 구현

---

src/main/java/com/sparta/delivery/domain/review/controller/ReviewController.java
src/main/java/com/sparta/delivery/domain/review/dto/ReviewRequestDto.java
src/main/java/com/sparta/delivery/domain/review/dto/ReviewResponseDto.java
src/main/java/com/sparta/delivery/domain/review/dto/ReviewUpdateRequestDto.java
src/main/java/com/sparta/delivery/domain/review/entity/Review.java
src/main/java/com/sparta/delivery/domain/review/repository/ReviewRepository.java
src/main/java/com/sparta/delivery/domain/review/service/ReviewService.java

review API 중 검색 기능 제외하고 모두 개발 완료
store에 리뷰 개수 및 전체별점 수정하는 코드 추가 후 리뷰에 해당 코드 추가 예정

feature: review API 개발

---

src/main/java/com/sparta/delivery/domain/delivery_address/service/DeliveryAddressService.java
src/test/java/com/sparta/delivery/deliveryAddressTest/deliveryAddressTest.java

- create
배송지 등록 성공
배송지 등록 실패 - 유저의 중복된 배송지명이 존재하는 경우
배송지 등록 실패 - 유저의 배송지 수가 3개 이상인 경우
- read
배송지 단일 조회 성공
배송지 단일 조회 실패
모든 배송지 조회 성공
모든 배송지 조회 실패 - 결과 없는 경우
- update
배송지 정보 수정 성공
배송지 정보 수정 실패 - 권한 없음
- delete
배송지 삭제 성공
배송지 삭제 실패

<배송지> 배송지 Test 코드 구현

---

src/test/java/com/sparta/delivery/deliveryAddressTest/deliveryAddressServiceTest.java

refactor : deliveryAddressServiceTest

---

src/main/java/com/sparta/delivery/domain/order/dto/OrderRequestDto.java
src/main/java/com/sparta/delivery/domain/order/service/OrderService.java

fix: order service 수정

---

src/main/java/com/sparta/delivery/domain/store/controller/StoreController.java
src/main/java/com/sparta/delivery/domain/store/service/StoreService.java

변경 내용 : ResponseEntity<Object>->ResponseEntity<?>

refactor:가게삭제시 deletedAt검사로 쿼리개선,responseEntity제네릭 변경

---

src/main/java/com/sparta/delivery/domain/order/entity/Order.java
src/main/java/com/sparta/delivery/domain/order/service/OrderService.java
src/main/java/com/sparta/delivery/domain/orderProduct/entity/OrderProduct.java
src/main/java/com/sparta/delivery/domain/orderProduct/repository/OrderProductRepository.java

orderProduct entity 및 repository 추가
orderEntity에 orderProduct와의 연관관계 추가
orderService -> 주문 생성, 수정에 주문상품 테이블에 상품 추가하는 코드 추가

feature: orderProduct 추가

---

src/main/java/com/sparta/delivery/config/global/exception/GlobalExceptionHandler.java
src/main/java/com/sparta/delivery/config/global/exception/custom/RegionNotFoundException.java
src/main/java/com/sparta/delivery/domain/region/controller/RegionController.java
src/main/java/com/sparta/delivery/domain/region/dto/RegionReqDto.java
src/main/java/com/sparta/delivery/domain/region/dto/RegionResDto.java
src/main/java/com/sparta/delivery/domain/region/entity/Region.java
src/main/java/com/sparta/delivery/domain/region/repository/RegionRepository.java
src/main/java/com/sparta/delivery/domain/region/service/RegionService.java
src/main/java/com/sparta/delivery/domain/store/controller/StoreController.java
src/main/java/com/sparta/delivery/domain/store/dto/StoreResDto.java
src/main/java/com/sparta/delivery/domain/store/entity/Stores.java
src/main/java/com/sparta/delivery/domain/store/repository/StoreRepository.java
src/main/java/com/sparta/delivery/domain/store/repository/StoreRepositoryCustom.java
src/main/java/com/sparta/delivery/domain/store/repository/StoreRepositoryImpl.java
src/main/java/com/sparta/delivery/domain/store/service/StoreService.java

fix: 리뷰별점합 계산 메서드 추가,  코드리펙터링

---

src/test/java/com/sparta/delivery/userTest/UserServiceTest.java

- jwt 발급 로직이 변경되어 로그인 테스트도 수정했습니다.
- 기능은 동일합니다

refactor: testAuthenticateUserSuccess Test 수정

---

src/main/java/com/sparta/delivery/config/PageableConfig.java
src/main/java/com/sparta/delivery/domain/review/controller/ReviewController.java
src/main/java/com/sparta/delivery/domain/review/dto/ReviewRequestDto.java
src/main/java/com/sparta/delivery/domain/review/entity/Review.java
src/main/java/com/sparta/delivery/domain/review/repository/ReviewRepository.java
src/main/java/com/sparta/delivery/domain/review/service/ReviewService.java
src/main/java/com/sparta/delivery/domain/store/entity/Stores.java

PageableConfig 클래스 생성
->  해당 클래스의 createPageRequest 호출 시 pageable 객체 생성
리뷰 컨트롤러에 적용

feature: pageable 클래스 생성 및 리뷰에 적용

---

src/main/java/com/sparta/delivery/domain/delivery_address/controller/DeliveryAddressController.java
src/main/java/com/sparta/delivery/domain/delivery_address/swagger/DeliveryAddressSwaggerDocs.java
src/main/java/com/sparta/delivery/domain/user/swagger/UserSwaggerDocs.java

- DeliveryAddressController 의 Swagger 문서화 및 응답 코드 설명 적용

feat : DeliveryAddressSwaggerDocs 커스텀 어노테이션 추가 및 Swagger 응답 설정

---

Dockerfile

feat : 도커파일 설정

---

src/main/java/com/sparta/delivery/config/global/exception/GlobalExceptionHandler.java
src/main/java/com/sparta/delivery/domain/delivery_address/swagger/DeliveryAddressSwaggerDocs.java
src/main/java/com/sparta/delivery/domain/token/controller/JwtController.java
src/main/java/com/sparta/delivery/domain/token/swagger/TokenSwaggerDocs.java
src/main/java/com/sparta/delivery/domain/user/swagger/UserSwaggerDocs.java

- JwtController 의 Swagger 문서화 및 응답 코드 설명 적용
- UserSwaggerDocs , DeliveryAddressSwaggerDocs 의 엑세스토큰, 쿠키 포함 여부 추가

feat : TokenSwaggerDocs 커스텀 어노테이션 추가 및 Swagger 응답 설정

---

src/main/java/com/sparta/delivery/domain/card/repository/CardRepository.java
src/main/java/com/sparta/delivery/domain/card/service/CardService.java
src/main/java/com/sparta/delivery/domain/payment/controller/PaymentController.java
src/main/java/com/sparta/delivery/domain/payment/repository/PaymentRepository.java
src/main/java/com/sparta/delivery/domain/payment/service/PaymentService.java
src/test/java/com/sparta/delivery/cardTest/CardServiceTest.java
src/test/java/com/sparta/delivery/paymentTest/PaymentServiceTest.java

- 로그인한 card와 payment를 가져오도록 수정
- 결제 전인지 확인하는 코드 추가
- 테스트 변경
- return type 통일
- 중복 메서드 제거

refactor : card, payment 수정

---

.github/workflows/deploy-delivery.yml
.gitignore

feat : gitignore 파일 수정, github workflows 작성

feat : gitignore 파일 수정, github workflows 작성

---

src/main/java/com/sparta/delivery/domain/region/controller/RegionController.java
src/main/java/com/sparta/delivery/domain/region/dto/RegionListDto.java
src/main/java/com/sparta/delivery/domain/store/controller/StoreController.java
src/main/java/com/sparta/delivery/domain/store/dto/StoreRegionResDto.java
src/main/java/com/sparta/delivery/domain/store/dto/StoreReqDto.java
src/main/java/com/sparta/delivery/domain/store/entity/Stores.java
src/main/java/com/sparta/delivery/domain/store/enums/Category.java
src/main/java/com/sparta/delivery/domain/store/service/StoreService.java
src/test/java/com/sparta/delivery/storeTest/StoreServiceTest.java

- 예외처리 기능 코드 추가 및 변경
- 가게조회시 지역리스트 보기위한 dto추가
- 삭제기능 : delete->patch변경가게삭제처리시 지역도 삭제처리되게 변경
- operational 어노테이션 추가(stores)
- 기타코드 수정

fix : 지역정보를 불러오기위한 구조변경,삭제코드변경,기타 코드변경

---

.github/workflows/deploy-delivery.yml
.gitignore
build.gradle
docker-compose.yml
src/main/resources/application.yml
src/test/java/com/sparta/delivery/DeliveryApplicationTests.java
src/test/java/com/sparta/delivery/aiTest/integration/AiTest.java

feat : application.yml 파일 생성

---

src/main/java/com/sparta/delivery/domain/token/service/JwtServiceImpl.java
src/main/java/com/sparta/delivery/domain/token/service/JwtUtil.java
src/main/java/com/sparta/delivery/domain/token/service/RefreshTokenServiceImpl.java
src/main/java/com/sparta/delivery/domain/user/controller/UserController.java
src/main/java/com/sparta/delivery/domain/user/dto/AuthTokenData.java
src/main/java/com/sparta/delivery/domain/user/repository/UserRepository.java
src/main/java/com/sparta/delivery/domain/user/service/UserService.java
src/test/java/com/sparta/delivery/userTest/UserServiceTest.java

- @Valid 어노테이션 위치 변경
- UserService 메서드 설명 주석 추가
- RefreshTokenServiceImpl 메서드 설명 주석 추가
- JwtServiceImpl 메서드 설명 주석 추가
- - JwtResponseDto 클래스 용도에 맞게 AuthTokenData로 이름 변경
- UserRepository 에서 사용하지 않는 메서드 제거

refactor : User 및 token 서비스 메서드 설명 주석 추가

---

README.md
src/main/java/com/sparta/delivery/domain/region/controller/RegionController.java
src/main/java/com/sparta/delivery/domain/region/dto/RegionReqDto.java
src/main/java/com/sparta/delivery/domain/region/service/RegionService.java
src/main/java/com/sparta/delivery/domain/region/swagger/RegionSwaggerDocs.java
src/main/java/com/sparta/delivery/domain/store/controller/StoreController.java
src/main/java/com/sparta/delivery/domain/store/repository/StoreRepository.java
src/main/java/com/sparta/delivery/domain/store/service/StoreService.java
src/main/java/com/sparta/delivery/domain/store/swagger/StoreSwaggerDocs.java
src/test/java/com/sparta/delivery/regionTest/RegionServiceTest.java
src/test/java/com/sparta/delivery/storeTest/StoreServiceTest.java

- Region service, Controller 수정, storeRepository수정
- Swagger docs 코드 작성
- 지역/가게 삭제시 인증 추가
- 운영지역 광화문주소인 초기값으로고정(province:도시, city:서울)
- 동은 광화문 인근 3가지만가능하게 코드추가(도렴동,적선동,중학동)
- 기타 불필요한 코드 개선 혹은 삭제

feat : swaggerdocs수정, 기타 코드 세부사항 수정

---

src/main/java/com/sparta/delivery/config/PageableConfig.java
src/main/java/com/sparta/delivery/config/global/exception/custom/OrderModificationNotAllowedException.java
src/main/java/com/sparta/delivery/config/global/exception/custom/OrderNotFoundException.java
src/main/java/com/sparta/delivery/config/global/exception/custom/ProductSelectionRequiredException.java
src/main/java/com/sparta/delivery/config/global/exception/custom/ReviewNotAllowedException.java
src/main/java/com/sparta/delivery/config/global/exception/custom/ReviewNotFoundException.java
src/main/java/com/sparta/delivery/config/global/exception/custom/UserOrderNotFoundException.java
src/main/java/com/sparta/delivery/domain/order/controller/OrderController.java
src/main/java/com/sparta/delivery/domain/order/repository/OrderRepository.java
src/main/java/com/sparta/delivery/domain/order/service/OrderService.java
src/main/java/com/sparta/delivery/domain/orderProduct/repository/OrderProductRepository.java
src/main/java/com/sparta/delivery/domain/product/entity/Product.java
src/main/java/com/sparta/delivery/domain/product/service/ProductService.java
src/main/java/com/sparta/delivery/domain/review/controller/ReviewController.java
src/main/java/com/sparta/delivery/domain/review/repository/ReviewRepository.java
src/main/java/com/sparta/delivery/domain/review/service/ReviewService.java

order, review custom 예외처리
order 생성/수정/삭제 시 상품 개수 변경
상품 개수 0개 시 품절 오류 thow
리뷰 및 주문 검색 기능 추가

fix: order, review custom 예외처리

---

.github/workflows/deploy-delivery.yml
.gitignore
Dockerfile
docker-compose.yml
src/main/java/com/sparta/delivery/domain/ai/service/AiService.java
src/main/resources/application.yml

refactor : yml 설정 변경

---

src/main/java/com/sparta/delivery/config/PageableConfig.java
src/main/java/com/sparta/delivery/config/global/exception/GlobalExceptionHandler.java
src/main/java/com/sparta/delivery/config/global/exception/custom/NotStoreOwnerException.java
src/main/java/com/sparta/delivery/config/global/exception/custom/NotStoreProductException.java
src/main/java/com/sparta/delivery/config/global/exception/custom/ProductQuantityNotAllowedException.java
src/main/java/com/sparta/delivery/config/global/exception/custom/ReviewAlreadyExistsException.java
src/main/java/com/sparta/delivery/domain/order/controller/OrderController.java
src/main/java/com/sparta/delivery/domain/order/service/OrderService.java
src/main/java/com/sparta/delivery/domain/order/swagger/OrderSwaggerDocs.java
src/main/java/com/sparta/delivery/domain/product/service/ProductService.java
src/main/java/com/sparta/delivery/domain/review/controller/ReviewController.java
src/main/java/com/sparta/delivery/domain/review/repository/ReviewRepository.java
src/main/java/com/sparta/delivery/domain/review/service/ReviewService.java
src/main/java/com/sparta/delivery/domain/review/swagger/ReviewSwaggerDocs.java

order, review -> swagger docs 작성 및 controller 코드에 추가
주문 생성, 리뷰 작성에 예외 처리 추가

feature: swagger docs 작성

---

.github/workflows/deploy-delivery.yml
docker-compose.yml

feat : 무중단배포 설정

---

src/main/java/com/sparta/delivery/domain/ai/service/AiService.java

```json
{
"question":"만두 상품의 이름을 추천해줘" // + " 답변을 최대한 간결하게 50자 이하로"
}
{
"answer": "오늘만두, 맘스키친, 빚은만두, 꽉찬만두, 행복만두\n"
}
{
"answer": "오늘의 만두, 갓 만든 만두, 찜만두,  행복만두,  명품만두\n"
}
```
```json
{
"question":"만두 상품의 이름을 추천해줘" // + " 속담 활용해 답변을 최대한 간결하게 50자 이하로"
}
{
"answer": "* **입안가득 만두:**  '입안에 넣으면 톡 터지는 맛'을 표현\n* **금상첨화 만두:** '최고의 만두'라는 의미를 담아\n* **황금만두:**  고급스럽고 귀한 만두라는 느낌\n* **만두왕:**  만두의 최고봉을 뜻하는 압도적인 이름\n* **복만두:** 복을 기원하는 긍정적인 이미지 부여\n"
}
{
"answer": "* 콩 심은 데 콩 나고 팥 심은 데 팥 나는 **콩팥만두**\n* 빚 좋은 개살구 **개살구만두** (색다른 만두일 때)\n* 팔방미인 **팔방만두** (다양한 속 재료 사용시)\n"
}
```
```json
{
"question":"만두 상품의 이름을 추천해줘" // + " 속담 활용해, 트렌디하고 독특하게 해, 이모지 사용해, 답변을 최대한 간결하게 50자 이하로"
}
{
"answer": "심봤다! 왕만두🥟  금싸라기 찐만두🥟  콩 심은데 콩 나듯 든든만두🥟\n"
}
{
"answer": "금강산도 식후경🥟🥢  호랑이도 제 말하면 발 떤다🐅🐾  콩 심은 데 콩 나고 팥 심은 데 팥 난다 🫘🥟\n"
}
``` …

AI 텍스트 추천 고도화

---

src/main/java/com/sparta/delivery/domain/order/controller/OrderController.java
src/main/java/com/sparta/delivery/domain/order/dto/OrderRequestDto.java
src/main/java/com/sparta/delivery/domain/order/dto/OrderStatusRequestDto.java
src/main/java/com/sparta/delivery/domain/order/entity/Order.java
src/main/java/com/sparta/delivery/domain/order/service/OrderService.java
src/main/java/com/sparta/delivery/domain/orderProduct/entity/OrderProduct.java
src/main/java/com/sparta/delivery/domain/review/controller/ReviewController.java
src/test/java/com/sparta/delivery/orderTest/OrderServiceTest.java

feature: OrderTest 작성

---

src/main/java/com/sparta/delivery/config/SecurityConfig.java
src/main/java/com/sparta/delivery/config/filter/JwtAuthenticationFilter.java
src/main/java/com/sparta/delivery/domain/user/enums/UserRoles.java

- 결제정보 삭제 -> MASTER
- 가게추가 -> MANAGER, MASTER
- 상품 -> READ를 제외한 모든 접근 OWNER, MANAGER, MASTER
- AI -> OWNER, MANAGER, MASTER
- 운영지역 -> READ를 제외한 모든 접근 OWNER, MANAGER, MASTER
(DELETE -> PATHCH 로 통일해야해서 추가안했음)
일단 제가 생각하기에 권한에 따라 접근이 제한 되어야하는? 경로를 정리했어요
오더나 다른 부분은 같이 얘기하고 접근 제한하는게 맞을 거 같아서 처리안했어요!

feat: 도메인별 Security Http 접근 권한 설정

---

src/main/java/com/sparta/delivery/domain/order/dto/OrderListResponseWithReviewDto.java
src/main/java/com/sparta/delivery/domain/order/dto/OrderRequestDto.java
src/main/java/com/sparta/delivery/domain/order/dto/OrderStatusRequestDto.java
src/main/java/com/sparta/delivery/domain/order/entity/Order.java
src/main/java/com/sparta/delivery/domain/order/service/OrderService.java
src/main/java/com/sparta/delivery/domain/review/dto/ReviewRequestDto.java
src/main/java/com/sparta/delivery/domain/review/dto/ReviewUpdateRequestDto.java
src/main/java/com/sparta/delivery/domain/review/service/ReviewService.java
src/test/java/com/sparta/delivery/ReviewTest/ReviewServiceTest.java
src/test/java/com/sparta/delivery/orderTest/OrderServiceTest.java

리뷰 테스트코드 작성
리뷰 삭제/수정 검증 로직 추가
유저 주문 조회 시 해당 리뷰까지 같이 가져오도록 수정

feature: ReviewTest 작성
